
editor_sources = files(
    'editor_assets.cpp',
    'editor_engine.cpp',
    'editor_main.cpp',
    'editor_mapgen_func.cpp',
    'editor_mapgen_piece.cpp',
    'editor_me_editable_id.cpp',
    'editor_me_state_export.cpp',
    'editor_me_state_serde.cpp',
    'editor_me_state.cpp',
    'editor_projects.cpp',
    'editor_widget_combofilter.cpp',
    'editor_widgets.cpp',
    'fts_fuzzy_match.cpp',
    'ImGuiFileDialog.cpp',
)
