name: Clang-tidy (clang-12, tiles)

on:
  push:
    branches:
    - upload
  pull_request:
    branches:
    - upload

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
        CMAKE: 1
        CLANG: clang++-12
        COMPILER: clang++-12
        CATA_CLANG_TIDY: plugin
        TILES: 1
        SOUND: 1
    steps:
    - name: checkout repository
      uses: actions/checkout@v1
      with:
        fetch-depth: 10
    - name: install dependencies
      run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main"
          sudo apt-get update
          sudo apt-get install libncursesw5-dev clang-12 libclang-12-dev llvm-12-dev llvm-12-tools \
            libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev libpulse-dev ccache \
            gettext
    - name: prepare
      run: bash ./build-scripts/requirements.sh
    - name: run clang-tidy
      run: bash ./build-scripts/build.sh
